### PR TITLE
Riemann solver corrections for 2D SWE equations

### PR DESCRIPTION
**Pull request by mandli**
This is not quite working still but at least works with out bathymetry.  Currently the flux difference does not seem to cancel correctly.  In other words, in a steady state configuration the flux difference and the source terms should subtract to zero:
```
delta_phi = 0.5 * g * hR**2 - 0.5 * g * hL**2 + hR * uR**2 - hL * uL**2
delta_s = 0.5 * g * (hR + hL) * (bR - bL)
delta_phi - delta_s = 0.5 * g * hR**2 - 0.5 * g * hL**2 + hR * uR**2 - hL * uL**2 - 0.5 * g * (hR + hL) * (bR - bL)
delta_phi - delta_s = 0.5 * g * (hR**2 - hL**2) - 0.5 * g * (hR + hL) * (bR - bL)
delta_phi - delta_s = 0.5 * g * (hR - hL) * (hR + hL) - 0.5 * g * (hR + hL) * (bR - bL)
```
Since the sea-surface would be zero then `(hR - hL) == (bR - bL)` and the expression equates to zero.  Currently this is not the case.

### CODE REVIEW

**Comment by mandli** [comment]
Just to be clear I am assuming currently that I am doing something stupid and just not seeing what.

**Comment by mandli** [comment]
After further investigation this may actually work and it was another issue with the test.  Someone else should probably look at this though before we conclude this is good to go.

**Comment by ketch** [comment]
The test passes for me and the solution looks reasonable.

**Comment by ketch** [comment]
I think we can go ahead and merge but will wait for your okay since it still says (WIP).

**Comment by mandli** [comment]
Ok, I removed one check.  There are some improvements that could be made but most are at the cost of readability so I am ok with merging this in.  I might take a crack at the transverse solver as well over the next week.

**Comment by mandli** [comment]
Added a transverse solver now.

**Pull request merged**
