### PR TITLE
Update branch, add testing workflow, use implicit none in more Riemann solvers

### PR DESCRIPTION
**Pull request by carlosmunozmoncayo**
With these changes, there are no longer variables with implicit data type in the Riemann solvers. For the moment, the testing workflow is using PyClaw's tests.

### CODE REVIEW

**Comment by carlosmunozmoncayo** [comment]
The behavior of one Riemann solver seems to have changed. The regression tests in `clawpack/amrclaw/tests/acoustics_2d_adjoint` are failing in the CI workflow and locally for me. Please do not merge this yet, I'll try to find out what happened.

**Comment by ketch** [comment]
That's very strange, since it's hard to see what is different about that example.  I took a quick look but didn't spot anything that seemed likely to cause a problem.

**Comment by carlosmunozmoncayo** [comment]
The same test fails if I use the Riemann solvers without the modifications in this PR. The difference between the expected and reference solutions is also the same. I think that the behavior of the Riemann solver was not affected.

**Comment by ketch** [comment]
Okay.  In that case I will merge this and open a PR to the master branch.

**Pull request merged**
